### ISSUE TITLE
Possible with MathJax from CDN?

### ISSUE THREAD

**Issue by queejie** [pkra/mathjax-img#13]
I'd really love to use this, but I am unable to get it to work with the MathJax CDN.  It seems to load if I remove the [img] prefix in the loader, but does not work or result in any error messages.  Is it only possible if I build it all locally?  Thanks.

Also, there is a difference in the top of the img.js file vs the documentation on the order of the arguments.  I'm not sure what to try:
````
\img{http://url.to.img}['top','10px','10px']
````
or
````
\img['top','10px','10px']{http://url.to.img}
````

![image](https://user-images.githubusercontent.com/1616827/122822717-6e335d80-d2ac-11eb-844c-a30d2d3b2ec9.png)

**Comment by pkra** [comment]
> I am unable to get it to work with the MathJax CDN.

For MathJax v3, see https://github.com/pkra/mathjax-img#using-a-browser

>  Also, there is a difference in the top of the img.js file vs the documentation on the order of the arguments. I'm not sure what to try:

The readme is right. Thanks for pointing this discrepancy out - I've removed the outdated comment from the js file.

**Comment by queejie** [comment]
Thanks very much!  For some reason I saw the wrong 'paths' parameter there.  I no longer have any console errors.  

I've tried many permutations, with and without quotes in various places, with and without an http prefix, with local and remote images:

````
\img[valign=‘top’,width=‘100px’,height=‘100px’]{/assets/PLS-logo.png}
\img[valign=‘top’,width=‘100px’,height=‘100px’]{‘/assets/PLS-logo.png’}
\img[valign=top,width=100px,height=100px]{/assets/PLS-logo.png}

\img[valign=‘top’,width=‘100px’,height=‘100px’]{https://localhost:4200/assets/PLS-logo.png}
\img[valign=top,width=100px,height=100px]{https://localhost:4200/assets/PLS-logo.png}

\img[top,100px,100px]{https://localhost:4200/assets/PLS-logo.png}
\img[top,100px,100px]{/assets/PLS-logo.png}
\img[‘top’,’100px’,’100px’]{‘/assets/PLS-logo.png’}
````

The result is always `\img` in red, from MathJax.  I'm developing a formula editor, and MathJax is working for every other element I've incorporate so far.  Any suggestions on which of these permutations is correct and/or if I am missing something?

![image](https://user-images.githubusercontent.com/1616827/122941317-480ccc80-d343-11eb-9462-6e913adcf917.png)

**Comment by queejie** [comment]
Thanks very much!  For some reason I saw the wrong 'paths' parameter there.  I still get one console error.

````
Uncaught TypeError: Cannot read property 'tex' of undefined
````  

I've tried many permutations, with and without quotes in various places, with and without an http prefix, with local and remote images:

````
\img[valign=‘top’,width=‘100px’,height=‘100px’]{/assets/PLS-logo.png}
\img[valign=‘top’,width=‘100px’,height=‘100px’]{‘/assets/PLS-logo.png’}
\img[valign=top,width=100px,height=100px]{/assets/PLS-logo.png}
\img[valign=‘top’,width=‘100px’,height=‘100px’]{https://localhost:4200/assets/PLS-logo.png}
\img[valign=top,width=100px,height=100px]{https://localhost:4200/assets/PLS-logo.png}
\img[top,100px,100px]{https://localhost:4200/assets/PLS-logo.png}
\img[top,100px,100px]{/assets/PLS-logo.png}
\img[‘top’,’100px’,’100px’]{‘/assets/PLS-logo.png’}
````

The result is either empty or `Undefined control sequence`, from MathJax.  I’m guessing this is from the missing tex issue above.  I'm developing a formula editor, and MathJax is working for every other element I've incorporated so far.  Any suggestions on which of these permutations is correct and/or if I am missing something?

![image](https://user-images.githubusercontent.com/1616827/122951251-23b4ee00-d34b-11eb-930f-47815d1161bb.png)

````
<script>
MathJax = {
	chtml: {mtextFont: 'arial unicode ms', mtextInheritFont: true,},
	svg: {mtextFont: 'arial unicode ms', mtextInheritFont: true,},
	loader: {
		load: [
			'input/tex-full', 'input/mml', 'output/svg', 'ui/menu', 'ui/safe',
			'a11y/semantic-enrich', 'a11y/complexity', 'a11y/explorer', 'a11y/assistive-mml',
			'[img]/img.min.js',
		],
		paths: {img: 'https://cdn.jsdelivr.net/npm/mathjax-img@3'}
	},
	tex: {
		packages: {'[+]': ['tex','img']}
	}
};
</script>
<script type="text/javascript" id="MathJax-script" src="//cdn.jsdelivr.net/npm/mathjax@3.1.4/es5/startup.js"></script>

````

**Comment by pkra** [comment]
I don't know the innards of startup.js I'm afraid.

The following works for me

```js
<script>
MathJax = {
	loader: {
		load: [
			'[img]/img.min.js',
		],
		paths: {img: 'https://cdn.jsdelivr.net/npm/mathjax-img@3'}
	},
	tex: {
		packages: {'[+]': ['img']}
	}
};
</script>
<script type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>

$$\img[width=400px]{https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg?download}$$
```

You might want to ask the MathJax team how to load third party extensions when using startup.js.

**Comment by pkra** [comment]
Sorry for not being more helpful here. There might very well be a bug on this end. Feel free to point me to the conversation.
